@BoLagom.Api_HostAddress = https://localhost:8000

### Hämta alla fastigheter
GET {{BoLagom.Api_HostAddress}}/api/properties/
Accept: application/json

### Hämta fastighet baserat på ID

GET {{BoLagom.Api_HostAddress}}/api/properties/1
Accept: application/json

### Skapa fastighet

POST {{BoLagom.Api_HostAddress}}/api/properties
Accept: application/json
Content-Type: application/json

{
  "name": "Tornet", 
  "address": "Landskronavägen 1, Helsingborg",
  "portCode": "1234"
}

### Radera fastighet

DELETE {{BoLagom.Api_HostAddress}}/api/properties/1
Accept: application/json


### Uppdatera fastighet

PUT {{BoLagom.Api_HostAddress}}/api/properties/3
Accept: application/json
Content-Type: application/json

{
  "name": "Gammelstugan",
  "address": "Kullagatan 10, 252 00 Helsingborg",
  "portCode": "1234"
}
